User Based Recommendation Model

In [ ]:
# Import the necessary libraries
import pandas as pd
import numpy as np

In [5]:
# Import the dataset
colnames=['user_id', 'movie_id', 'rating', 'timestamp'] 
df = pd.read_csv('Recommend.csv', names=colnames, header=None)
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [16]:
# Split the training & test datasets
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0]
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df,test_size=0.25)
display(n_users,n_movies)

943

1682

In [8]:
train_data.itertuples()

In [10]:
# Populate the train test matrices with random ratings
train_data_matrix = np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [14]:
train_data_matrix.shape

(943, 1682)

In [17]:
test_data_matrix = np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [18]:
test_data_matrix.shape

(943, 1682)

In [19]:
# Create cosine similarity matrices for users and movies and perform predictions
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff = train_data_matrix - mean_user_rating
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).
                                                                          sum(axis=1)]).T
user_pred

array([[ 1.56790941,  0.60577487,  0.49459319, ...,  0.30517972,
         0.30527464,  0.30511914],
       [ 1.29241934,  0.31567429,  0.16023189, ..., -0.0599134 ,
        -0.0584023 , -0.05840966],
       [ 1.29665837,  0.26674462,  0.11515526, ..., -0.1090071 ,
        -0.10708768, -0.10707063],
       ...,
       [ 1.17383144,  0.23755011,  0.08877738, ..., -0.12367514,
        -0.12265519, -0.12272056],
       [ 1.3151449 ,  0.31626478,  0.19384109, ..., -0.02395985,
        -0.02308191, -0.02275253],
       [ 1.38286304,  0.39936316,  0.29848373, ...,  0.10602523,
         0.10594695,  0.1059531 ]])